## "Numerical Python" 
### Pacote para computação científica com Python

###### Importando a biblioteca NumPy

In [3]:
from numpy import *   #importar todas as funções do NumPy

###### Definindo uma lista de valores

In [4]:
lst1 = [10, 2, 3]
lst2 = [1, 5, 1]
lst3 = [2, 3, 10]


###### Definindo uma lista de listas

In [6]:
A = [lst1, lst2, lst3]   
#Alternativamente: A = [[10, 2, 3],[1, 5, 1],[2, 3, 10]]

###### Criando um "array" (série ou matriz de valores)
Um array é semelhante à uma lista, mas pode ser manipulado por várias funções contidas no módulo numpy.<br>O tamanho de um array é imutável e nenhum elemento vazio é permitido.
<br><br>**Comandos para criar array:**<br>*array(list,dtype = type specificaton)*<br>*zeros((dim1,dim2),dtype = type specification)*<br>*ones((dim1,dim2),dtype = type specification)*<br>*identity(int,dtype = type specification)*<br>*arange(from,to,increment)*


In [35]:
A = array(A, float)              #array(list,dtype = type specificaton)
print(A)

[[10.  2.  3.]
 [ 1.  5.  1.]
 [ 2.  3. 10.]]


In [36]:
Z = zeros((3, 3))                #zeros((dim1,dim2),dtype = type specification)
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [37]:
O = ones((3, 3))                 #ones((dim1,dim2),dtype = type specification)
print(O)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [38]:
I = identity(3)                  #identity(int,dtype = type specification)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
R = arange(0.1, 1, 0.1)          #arange(from,to,increment)
print(R)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
### Acessando e alterando elementos do array
##a = zeros((3,3),dtype=int)
##print(a)
##a[0] = [2,3,0]              #Modificando uma linha
##print(a)
##a[2,0] = 5                  #Modificando um elemento
##print(a)
##a[1,0:2] = [8,-3]           #Modificando parte de uma linha
##print(a)
##a[:,2] = [1,1,3]            #Modificando uma coluna
##print(a)

In [ ]:
### Operações com arrays
##a = array([0, 4, 9, 16], float)
##print(a/16)
##print(a - 4.0)
##a = array([1.0, 4.0, 9.0, 16.0])
##print(sqrt(a))
##print(sin(a))


In [ ]:
### As funções importadas do módulo "math" funcionarão nos elementos individuais, mas não no próprio array.
##a = array([1.0, 4.0, 9.0, 16.0])
##from math import sqrt
##print(sqrt(a[1]))
##print(sqrt(a))
##from numpy import sqrt
##print(sqrt(a))


In [ ]:
### Array Functions
##from numpy import *
##A = array([[4,-2,1],[-2,4,-2],[1,-2,3]],dtype=float)
##b = array([1,4,3],dtype=float)
##print(diagonal(A))       # Diagonal principal
##print(diagonal(A,1))     # Primeira subdiagonal
##print(trace(A))          # Soma dos elementos da diagonal
##print(max(b))            # Valor do maior elemento
##print(argmax(b))         # Índice do maior elemento
##print(max((A)[0]))       # Valor do maior elemento da linha
##print(max((A)[:,0]))     # Valor do maior elemento da coluna
##print(argmax(A,axis=0))  # Indices dos menores elementos das colunas
##print(argmax(A,axis=1))  # Indices dos menores elementos das linhas


In [ ]:
### Produtos de matriz
##x = array([7,3])
##y = array([2,1])
##A = array([[1,2],[3,2]])
##B = array([[1,1],[2,2]])
##C = ones((3,2))
### Dot product
##print(dot(x,y))    # {x}.{y}
##print(dot(A,x))    # [A]{x}
##print(dot(A,B))    # [A][B]
##print(dot(A,C))    # [A][C]
### Inner product
##inner(x,y)  # {x}.{y}
##inner(A,x)  # [A]{x}
##inner(A,B)  # [A][B_transpose]
##inner(A,C)  # [A][C_transpose]


In [ ]:
### Módulo de Álgebra Linear
##from numpy import *
##from numpy.linalg import *
##A = array([[ 4.0, -2.0, 1.0],
##           [-2.0, 4.0, -2.0], 
##           [ 1.0, -2.0, 3.0]])
##b = array([1.0, 4.0, 2.0])
##print(inv(A))           # Intersa da matriz
##print('\n')
##print(solve(A,b))       # Solução do sistema linear [A]{x} = {b}


In [40]:
### Copying Arrays
'''
Se "a" é um array, o comando de atribuição "b = a" não resulta em um novo
objeto "b", mas simplesmente cria uma nova referência para "a", de modo que
uma alteração em "a" causa de mesma alteração em "b".
Para fazer uma cópia independente do array "a", use b = a.copy()
'''


'\nSe "a" é um array, o comando de atribuição "b = a" não resulta em um novo\nobjeto "b", mas simplesmente cria uma nova referência para "a", de modo que\numa alteração em "a" causa de mesma alteração em "b".\nPara fazer uma cópia independente do array "a", use b = a.copy()\n'