In [1]:
from numpy import *

In [2]:
#### Gauss Elimination Method

In [3]:
def gaussElimin(A,b):
    '''Resolve [A]{b}={x} pelo método da eliminação de Gauss.'''
    a = array(A, float)
    b = array(b, float)
    n = len(b)
    print(concatenate((a, array([b]).T), axis=1),'\n') #print da matriz ampliada
    # Eliminação
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                m = a[i,k]/a[k,k]
                a[i,k:n] = a[i,k:n] - m*a[k,k:n]
                b[i] = b[i] - m*b[k]
        print(concatenate((a, array([b]).T), axis=1),'\n') #print da matriz ampliada
    # Substituição retroativa
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b


In [13]:
# Testando
A = [[4,4,-1],[2,-3,1],[2,2,-3]]
b = [5,3,-1]
gaussElimin(A,b)


[[ 4.  4. -1.  5.]
 [ 2. -3.  1.  3.]
 [ 2.  2. -3. -1.]] 

[[ 4.   4.  -1.   5. ]
 [ 0.  -5.   1.5  0.5]
 [ 0.   0.  -2.5 -3.5]] 

[[ 4.   4.  -1.   5. ]
 [ 0.  -5.   1.5  0.5]
 [ 0.   0.  -2.5 -3.5]] 



array([1.28, 0.32, 1.4 ])

In [4]:
## Gauss-Jacobi Method

from numpy import *
 
def jacobi(a,b,x0=[0,0,0],tol=0.01,N=100):  
    '''Resolve [A]{b}={x} pelo método de Gauss-Jacobi.'''
    a = array(a, float)
    b = array(b, float)
    x0 = array(x0, float)
    n = len(b)
    x = zeros(n)      #gera vetor com n entradas, para comportar a solucao
    k = 0             #variavel contadora da iteracao

    #iteracoes  
    while (k < N):  
        k += 1  
        #Iteracao
        for i in arange(n):     #para cada entrada de posicao i do vetor x...  
            x[i] = b[i]         #some a entrada de posicao i do vetor b ...
            for j in concatenate((arange(0,i), arange(i+1,n))):  
                x[i] -= a[i,j]*x0[j]  #subtraia os termos da linha i da matriz de coefic. (exceto na diag. princ.)...
            x[i] /= a[i,i]      #e divida pelo termos de ordem i da diagonal principal.
        #tolerancia
        d = max(absolute(x-x0)) / max(absolute(x))
        print('k=%d, x=%s, d=%.5f'  %(k,x,d))
        if d <=tol:
            return x
        #prepara nova iteracao  
        x0 = copy(x)
    raise NameError('num. max. de iteracoes excedido.')


In [5]:
# Testando
A = [[4,-1,-1],[-2,6,1],[-1,1,7]]
b = [3,9,-6]
gaussElimin(A,b)


[[ 4. -1. -1.  3.]
 [-2.  6.  1.  9.]
 [-1.  1.  7. -6.]] 

[[ 4.   -1.   -1.    3.  ]
 [ 0.    5.5   0.5  10.5 ]
 [ 0.    0.75  6.75 -5.25]] 

[[ 4.         -1.         -1.          3.        ]
 [ 0.          5.5         0.5        10.5       ]
 [ 0.          0.          6.68181818 -6.68181818]] 



array([ 1.,  2., -1.])

In [6]:
# Testando
jacobi(A, b)


k=1, x=[ 0.75        1.5        -0.85714286], d=1.00000
k=2, x=[ 0.91071429  1.89285714 -0.96428571], d=0.20755
k=3, x=[ 0.98214286  1.96428571 -0.99744898], d=0.03636
k=4, x=[ 0.99170918  1.99362245 -0.99744898], d=0.01472
k=5, x=[ 0.99904337  1.99681122 -1.00027332], d=0.00367


array([ 0.99904337,  1.99681122, -1.00027332])

In [7]:
def seidel(a,b,x0=[0,0,0],tol=0.01,N=100):  
    ''' x = seidel(a,b).
        Solves [a]{b} = {x} by Gauss-Seidel iter method.'''
    a, b, x0 = array(a, float), array(b, float), array(x0, float)
    n = len(b)
    x = zeros(n) 
    k = 0        
    
    #iteracoes  
    while (k < N):  
        k += 1
        #iteracao de Seidel  
        for i in arange(n):             #para cada entrada de posicao i do vetor x ...
            x[i] = b[i]                 #some a entrada de posicao i do vetor b ...
            for j in arange(0,i):       #subtraia os produtos entre os termos da linha i da matriz de coefic.
                x[i] -= a[i,j]*x[j]     # e os valores xi já calculados...
            for j in arange(i+1,n):     
                x[i] -= a[i,j]*x0[j]
            x[i] /= a[i,i]              #e divida pelo termos de ordem i da diagonal principal.
        #tolerancia
        d = max(absolute(x-x0)) / max(absolute(x))
        print((k,x,d))
        if d <=tol:
            return x
        #prepara nova iteracao  
        x0 = copy(x)
    raise NameError('num. max. de iteracoes excedido.')


In [8]:
seidel(A, b)

(1, array([ 0.75,  1.75, -1.  ]), 1.0)
(2, array([ 0.9375    ,  1.97916667, -1.00595238]), 0.11578947368421055)
(3, array([ 0.99330357,  1.99875992, -1.00077948]), 0.027919096662116928)
(4, array([ 0.99949511,  1.99996162, -1.00006664]), 0.003095828972057836)


array([ 0.99949511,  1.99996162, -1.00006664])